settings:
  title: 'Status Page'
  url: 'https://cf-workers-status-page-production.lazbar.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: softkeys # unique identifier
    name: Softkeys
    url: 'https://www.softkeys.co.uk' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200

  - id: keysdash
    name: KeysDash
    url: 'https://www.keysdash.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: oftkeys
    name: Oftkeys
    url: 'https://www.oftkeys.com'
    method: GET
    expectStatus: 200
    followRedirect: false # should fetch follow redirects, default=false

  - id: activationmarket
    name: Activation Market
    url: 'https://activation.market'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
