name = "cf-workers-status-page"
workers_dev = true
account_id = ""
type = "webpack"
webpack_config = "node_modules/flareact/webpack"

[triggers]
crons = ["*/2 * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
kv-namespace = [{binding="KV_STATUS_PAGE", id="3b584e7536254b00a71b5cc3f40c40bd", preview_id="3b584e7536254b00a71b5cc3f40c40bd"}]
#zone_id="xxx"
#route="xxx"
